### ISSUE TITLE
Login into StarCommand fails

### ISSUE THREAD

**Issue by jnarboux** [StarExec/StarExec#271]
I can not use StarExec command.

java -jar StarExecCommand
login u=guest

I obtain: Error invalid user name or password.

Same result if i type my own login:

login u=narboux@unistra.fr p=mypassword

**Comment by sfiolic** [comment]
Hi there @jnarboux, Do you know the date or approximate month that the login errors began? Were you able to login before March (Nov, Dec, Jan, Feb)? 

Thanks,
Steve

**Comment by fabeulous** [comment]
Hi @sfiolic,
I found logs on our server indication that the login using StarExecCommand was still working mid February (14th to be precise).

I hope this helps,
Fabian

**Comment by sfiolic** [comment]
@fabeulous Thank you for the information, any chance you have a date of the first command that failed?

**Comment by jnarboux** [comment]
I was not using star exec command before .

Thanks

Regards

Julien

**Comment by sfiolic** [comment]
@jnarboux Thank you, we are looking into the issue. All of our schedules are strained for the next 2 weeks but we hope to make progress until we have more time to resolve StarexecCommand. 

Steve

**Comment by fabeulous** [comment]
> @fabeulous Thank you for the information, any chance you have a date of the first command that failed?

We only noticed on March 24 while doing some testing for the Confluence Competition. So @jnarboux saw the issue before us.

**Comment by astump** [comment]
Hi, all.  Thanks to investigations by @sfiolic and @alexander-r-brown I know what (must have) caused the problem: on March 4th, due to recently discovered security vulnerabilities in apache-tomcat-7.0.64, we upgraded to 7.0.100.  Undoubtedly this led to the change that Steve and Alex detected in headers that the server creates.  This insight should let us fix the problem in the next few days (I anticipate). Alex and Steve are busy finishing classes but I will investigate myself in the next couple days...

**Comment by jwaldmann** [comment]
Hi. 

It's great that starexec-command is working again (but does anonymous login work?) but it's not great that the messages in this issue here do absolutely nothing to help me understand what had to be changed, and why.

Please  - what is

> the change that Steve and Alex detected in headers that the server creates

I think that same change also broke  https://github.com/jwaldmann/star-exec-presenter/blob/master/src/Presenter/StarExec/Connection.hs - part of my tool for comparing results of several jobs (with common benchmarks). 

That's independent of the actual running of termcomp. But it's used by some participants (matchbox, multum-non-multa) for preparation - and these are frustrated now. Sure, there are other methods for presenting data, but this one was convenient.

I can guess that the relevant commit is https://github.com/StarExec/StarExec/commit/00fa3e414e2135aa77a8ee24b9beefbbd7a8b9cb but I don't understand what's happening there. Is `JSESSIONID` transmitted differently now?

I tried to look for a description of the change at https://tomcat.apache.org/tomcat-7.0-doc/changelog.html  and https://www.cvedetails.com/product/887/Apache-Tomcat.html?vendor_id=45  but I don't see anything.

Don't get me wrong - of course you're not responsible for the breakage (tomcat is) but if you had documented your process of debugging the issue, then it would have been helpful.
