### ISSUE TITLE
Web interface does not download file written in output dir

### ISSUE THREAD

**Issue by vuphan314** [StarExec/StarExec#301]
Hi @astump,

For job pair [513911764](https://www.starexec.org/starexec/secure/details/pair.jsp?id=513911764), my solver wrote a text file in the output dir given by `$2`. But when I downloaded `all output`, I only found a file for [`stdout`](https://github.com/StarExec/StarExec/files/6489364/513911764.txt), not for the written output file `/export/starexec/sandbox/output/output_files/preprocessed.cnf`.

The [job log](https://github.com/StarExec/StarExec/files/6489369/log.txt) shows that the result is correct.

**Comment by astump** [comment]
Hi, Vu.

For extra output files to be saved, this has to be explicitly indicated.
If you look at the start of your log file, you will see

05/16/21 04:57:25 AM CDT: stdout save option : 2
05/16/21 04:57:26 AM CDT: additional output save option : 1

If the option is 1, it means "do not save".  Otherwise, the file is saved.
This is why the jobscript is not saving your extra file.

Please double check how you are creating the job, to make sure this option
is enabled.  I forgot at the moment exactly how to enable it, by I hope you
find this in the job creation options.

Best,
Aaron
