### ISSUE TITLE
StarexecCommand: Login Fails

### ISSUE THREAD

**Issue by fabeulous** [StarExec/StarExec#306]
When using `StarexecCommand.jar` my login attempts fail with the error `Invalid username and/or password`.
This happens for both `u=guest`and `u=my@email.com p=...`. 
I have double-checked the email and password, both should be correct.

To reproduce the problem:
I download the latest `starexeccommand.zip` archive, extract it, and run:

```
> java -jar StarExecCommand.jar
Last update = July 10, 2017

StarCom> login u=guest
[.. connection debug info ..]
-- END --
ERROR: Invalid username and/or password

StarCom> login u=my@email.com p=mypassword
[.. connection debug info ..]
-- END --
ERROR: Invalid username and/or password
```

**Comment by astump** [comment]
Thanks for letting us know.  We have not double-checked StarExecCommand
since our upgrade to tomcat9.  Probably that has broken it.  I am CC'ing
Alex Brown, our developer, to look into this.
Aaron

**Comment by alexander-r-brown** [comment]
Hello, fabeulous,

Could you please specify your OS and Java installation version? 

Thank you for your time.

**Comment by fabeulous** [comment]
Hi Alex, thanks for looking into this.

I am running Linux (Arch Linux to be precise) and Java 1.8. In full detail:
```
> java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```

**Comment by alexander-r-brown** [comment]
Thank you for your reply.

It turns out that StarCom was experiencing two issues at once.

The first issue, as you reported, was that users could not log in.
The second issue, which I ran into whilst trying to solve the first, is that the app could not launch on versions of Java more recent than Java 8.

I believe these issues are fixed now.
On my end, I am now able to download StarCom and run the app on Java 16. I am also able to log in without issue.
Could you please confirm that this is working on your end now as well? 

Thank you again for you help in this matter.

**Comment by fabeulous** [comment]
Hi Alex. I just tested locally and on our servers, and everything is working fine. Thanks for the fast fix.
