### ISSUE TITLE
"url must start with http://" for "associated web site" in solver description

### ISSUE THREAD

**Issue by jwaldmann** [StarExec/StarExec#329]
This will reject https URLs. And I can't put them in the solver's "description", because #30 . 

So, for security reasons, we cannot use secure URLs? `/s`

**Comment by gg9192** [comment]
This bug is not intuitive to reproduce. As a sanity check for the existence of this bug, here are the steps to reproduce it. 

1. upload a solver.
2. go to explore spaces and find the uploaded solver
3. click on the URL in the name column for the solver table in the space where the solver exists. 
4. go to actions, edit solver.
5. see associated URL at the bottom
