### ISSUE TITLE
For standalone versions of job pages, preserve as much data as possible

### ISSUE THREAD

**Issue by astump** [StarExec/StarExec#361]
It seems that currently we do not preserve the solver output, and I think we should.  The logs cannot be preserved and are not necessary anyway for historical purposes.  But solver output we should keep.

**Comment by gg9192** [comment]
This is a High priority ticket. Pref done by next week

**Comment by gg9192** [comment]
I'm taking what I said previously back. If they just wanted the job output, they would have just downloaded it (something already implemented). This is a significant change, as half of what needs to be implemented hasn't been. 

The design choice I am making: 
- for each pair, the link redirects to root/pair_{pairid}.html. If its not all in one directory, we will have CSS problems
- in our datadir, the job outputs are stored by job id.
- there are some tricky cases to consider. see cases
- Due to the above fact, we have the popout redirect to /jobPairs/output/{pairId}/{stagenumber}.txt. If the number of stages is 1, we will use /jobPairs/output/{pairId}/{1}.txt, which requires the least change. If we don't have a unified format, contacting the strings to link to the full text popout is too complex
- keep in mind that somehow, this directory hierarchy needs to be preserved when downloaded

Heres what needs to be done at a high level:

- [x] make the items in the pairs table actually link to the jobpair page
- [x] make the jobpair page compatible with local job page
- [x] copy the solver output and somehow have it display in the pair page

**Comment by gg9192** [comment]
make the jobpair page compatible with local job page:
we want everything but (the job log and (actions: downloadAllOutPut, rerunPair))

**Comment by gg9192** [comment]
Cases to consider:
- If the pair is a pipeline, we have a dir that's named {$pairID} . In the directory, there are multiple text files named {$n}.txt, with n being the stagenumber. ex, 1.txt is the stdout for stage 1
- if the pair is a normal pair, we just have {$pairID}.txt .

**Comment by gg9192** [comment]
- [x] Unfortunately, many CSS files that are needed are missing. I need to find them and fix it. 
- [x] remove all the links
- [x] Make sure that the CSS and js needed by the job pair is copied
- [x] for each pair, fetch the data and put it into a HTML doc according to specs above
- [x] For each pair, fetch the job output and put it into the correct directory according to specs above

**Comment by gg9192** [comment]
Original for ref
<img width="768" alt="Screenshot 2023-07-14 at 16 00 54" src="https://github.com/StarExec/StarExec/assets/42902579/582b4d6b-97bc-496a-a53e-7ea498cc6c2a">
